name: Deploy Docker App + Terraform Infra

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        env:
          TF_VAR_public_ssh_key: ${{ secrets.VM_SSH_KEY }}
        run: terraform plan

      - name: Terraform Apply
        env:
          TF_VAR_public_ssh_key: ${{ secrets.VM_SSH_KEY }}
        run: terraform apply -auto-approve

  deploy:
    name: Deploy Docker App to Azure VM
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_IP }}
          username: azureuser
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker stop myapp || true
            docker rm myapp || true
            docker build -t my-nginx-app .
            docker run -d -p 80:80 --name myapp my-nginx-app
